export const festivalsContent = {
    en: {
        title: "Festivals & Awards",
        items: [
            { year: "2025", event: "Doclisboa", loc: "Portugal", detail: "Arché Lab" },
            { year: "2025", event: "Celaya Intl Film Festival", loc: "Mexico" },
            { year: "2025", event: "EUREKA Univ Film Festival", loc: "Colombia" },
            { year: "2025", event: "TIFF [Toronto International Film Festival]", loc: "Canada", detail: "Sponsored Guest" },
            { year: "2025", event: "FICUNAM", loc: "Mexico" },
            { year: "2024", event: "VITA Intl Short Film Festival", loc: "China" },
            { year: "2024", event: "YMotion", loc: "Portugal", award: "Best Script" },
            { year: "2024", event: "Caminhos do Cinema Português", loc: "Portugal" },
            { year: "2024", event: "SSIFF [San Sebastian International Film Festival]", loc: "Spain" },
            { year: "2024", event: "Indielisboa", loc: "Portugal" },
            { year: "2024", event: "Shortcutz Lisboa", loc: "Portugal" },
            { year: "2023", event: "Doclisboa", loc: "Portugal", detail: "Jury Member" },
            { year: "2022", event: "Beykoz Kundura", loc: "Turkey" },
            { year: "2022", event: "Shortage", loc: "Portugal" },
            { year: "2022", event: "Iconic Images", loc: "Lithuania" },
            { year: "2022", event: "Stockholm City Film Festival", loc: "Sweden" },
            { year: "2022", event: "Couch Film Festival", loc: "Canada" },
            { year: "2022", event: "Family Film Project", loc: "Portugal" },
            { year: "2022", event: "Entre Olhares", loc: "Portugal" },
            { year: "2022", event: "Triste Para Sempre", loc: "Portugal" },
            { year: "2021", event: "Doclisboa", loc: "Portugal", award: "Green Years Honorable Mention" },
            { year: "2021", event: "Cannes Film Festival", loc: "France", detail: "Focus Script Lab" },
            { year: "2020", event: "Cinema Verite", loc: "Iran" },
            { year: "2020", event: "Doclisboa", loc: "Macau" },
            { year: "2020", event: "Doclisboa", loc: "Portugal" },
            { year: "2020", event: "CineEco", loc: "Portugal" },
            { year: "2020", event: "Caminhos do Cinema Português", loc: "Portugal" },
            { year: "2020", event: "YMotion", loc: "Portugal", award: "Best Documentary" },
            { year: "2019", event: "Shortcutz", loc: "Portugal" },
            { 
                year: "2019", 
                event: "Doclisboa", 
                loc: "Portugal", 
                award: "Fernando Lopes Award for Best Portuguese First Film", 
                award2: "Pedro Fortes Award for Best Green Years Portuguese Film" 
            }
        ]
    },
    pt: {
        title: "Festivais & Prémios",
        items: [
            { year: "2025", event: "Doclisboa", loc: "Portugal", detail: "Arché Lab" },
            { year: "2025", event: "Celaya Intl Film Festival", loc: "México" },
            { year: "2025", event: "EUREKA Univ Film Festival", loc: "Colombia" },
            { year: "2025", event: "TIFF [Toronto International Film Festival]", loc: "Canadá", detail: "Convidado do Festival" },
            { year: "2025", event: "FICUNAM", loc: "México" },
            { year: "2024", event: "VITA Intl Short Film Festival", loc: "China" },
            { year: "2024", event: "YMotion", loc: "Portugal", award: "Melhor Argumento" },
            { year: "2024", event: "Caminhos do Cinema Português", loc: "Portugal" },
            { year: "2024", event: "SSIFF [San Sebastian International Film Festival]", loc: "Espanha" },
            { year: "2024", event: "Indielisboa", loc: "Portugal" },
            { year: "2024", event: "Shortcutz Lisboa", loc: "Portugal" },
            { year: "2023", event: "Doclisboa", loc: "Portugal", detail: "Membro do Júri" },
            { year: "2022", event: "Beykoz Kundura", loc: "Turquia" },
            { year: "2022", event: "Shortage", loc: "Portugal" },
            { year: "2022", event: "Iconic Images", loc: "Lituânia" },
            { year: "2022", event: "Stockholm City Film Festival", loc: "Suécia" },
            { year: "2022", event: "Couch Film Festival", loc: "Canadá" },
            { year: "2022", event: "Family Film Project", loc: "Portugal" },
            { year: "2022", event: "Entre Olhares", loc: "Portugal" },
            { year: "2022", event: "Triste Para Sempre", loc: "Portugal" },
            { year: "2021", event: "Doclisboa", loc: "Portugal", award: "Menção Honrosa Verdes Anos" },
            { year: "2021", event: "Cannes Film Festival", loc: "França", detail: "Lab Focus Script" },
            { year: "2020", event: "Cinema Verite", loc: "Irão" },
            { year: "2020", event: "Doclisboa", loc: "Macau" },
            { year: "2020", event: "Doclisboa", loc: "Portugal" },
            { year: "2020", event: "CineEco", loc: "Portugal" },
            { year: "2020", event: "Caminhos do Cinema Português", loc: "Portugal" },
            { year: "2020", event: "YMotion", loc: "Portugal", award: "Melhor Documentário" },
            { year: "2019", event: "Shortcutz", loc: "Portugal" },
            { 
                year: "2019", 
                event: "Doclisboa", 
                loc: "Portugal", 
                award: "Prémio Fernando Lopes para Melhor Primeiro Filme Português", 
                award2: "Prémio Pedro Fortes para Melhor Filme Português nos Verdes Anos" 
            }
        ]
    }
};